dist: xenial
sudo: required

services:
    - docker

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
  - node_modules

addons:
  chrome: stable

install:
  - yarn global add @angular/cli
  - yarn global add yalc
  - cd ~ && git clone -b fix/list-admin https://github.com/dasch-swiss/knora-api-js-lib.git && cd knora-api-js-lib && npm install && npm run yalc-publish
  - cd ~ && git clone -b api-js-lib/develop https://github.com/dasch-swiss/knora-ui.git && cd knora-ui && yalc add @knora/api && yarn install && yarn build-and-publish-prod
  - cd $TRAVIS_BUILD_DIR

script:
  - yarn yalc-add-modules
  - yarn test-ci
  - docker build .
