dist: xenial
sudo: required

services:
    - docker

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
  - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - yarn global add @angular/cli
  - yarn global add protractor
  - cd $TRAVIS_BUILD_DIR
  - yarn install

script:
  - yarn test-ci
  - yarn test-e2e-protractor
  - docker build .
