dist: xenial
sudo: required

services:
    - docker

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
  - node_modules

addons:
  chrome: stable

install:
  - yarn global add @angular/cli
  - yarn global add yalc
  - cd ~ && git clone -b wip/ontology-service https://github.com/dasch-swiss/knora-ui.git && cd knora-ui && yarn install && rm -rf dist/'@knora'/ && ng build @knora/core --prod && yalc publish dist/@knora/core
  - cd $TRAVIS_BUILD_DIR
  - rm -rf .yalc/@knora && yalc add @knora/core && yarn install --prod=false
  - yarn install

script:
  - yarn test-ci
  - yarn run webdriver-update
  - yarn test-e2e-protractor
  - yarn build-prod
  - docker build .
