dist: xenial
sudo: required

services:
    - docker

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
  - node_modules

addons:
  chrome: stable

install:
  - yarn global add @angular/cli
  # BEGIN: add unpublished module
  - yarn global add yalc
  - cd ~ && git clone -b wip/ontology-service https://github.com/dasch-swiss/knora-ui.git && cd knora-ui && yarn install && yarn build-and-publish-prod
  # END of "adding unpublished module"
  - cd $TRAVIS_BUILD_DIR
  - yalc add @knora/core
  - yarn install

script:
  - yarn test-ci
  - yarn run webdriver-update
  - yarn test-e2e-protractor
  - yarn build-prod
  - docker build .
