version: 2
jobs:
  build:
    docker:
    - image: angular/ngcontainer:latest
    - image: circleci/node:10-browsers
    working_directory: ~/repo

    steps:
      - run: sudo npm install yalc -g
      - run: cd ~ && git clone -b wip/ontology-service https://github.com/dasch-swiss/knora-ui.git && cd knora-ui && yarn install && rm -rf dist/'@knora'/ && ng build @knora/core --prod && yalc publish dist/@knora/core
      - run: cd ~/repo
      - run: rm -rf .yalc/@knora && yalc add @knora/core && yarn install --prod=false
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Version Info
          command: |
            node --version \
              && yarn --version \
              && git --version

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Build the libraries
      - run: yarn add --force node-sass
      - run: yarn build-prod

      # Run unit tests!
      - run: yarn ng test --watch=false --browsers=ChromeHeadless
      - run: yarn run webdriver-manager update --standalone false --gecko false --versions.chrome 2.37
      - run: yarn ng e2e --prod=true --protractor-config=./e2e/protractor-ci.conf.js --webdriver-update=false

      # Store build artefacts on circle
      - store_artifacts:
          path: ~/repo/dist
          destination: dist
