version: 2
jobs:
  build:
    docker:
    # - image: angular/ngcontainer:latest
    - image: circleci/node:10-browsers
    working_directory: ~/repo

    steps:
      - run: sudo npm install yalc -g
      - run: cd ~ && git clone -b master https://github.com/dasch-swiss/knora-api-js-lib.git && cd knora-api-js-lib && npm install && npm run yalc-publish
      - run: cd ~ && git clone -b master https://github.com/dasch-swiss/knora-ui.git && cd knora-ui && yalc add @knora/api && yarn install && yarn build-and-publish-prod
      - run: cd ~/repo
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Version Info
          command: |
            node --version \
              && yarn --version \
              && git --version

      - run: yarn yalc-add-modules
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Build the libraries
      - run: yarn add --force node-sass
      - run: yarn build

      # Run unit tests!
      - run: yarn ng test --watch=false --browsers=ChromeHeadless

      # Store build artefacts on circle
      - store_artifacts:
          path: ~/repo/dist
          destination: dist
